### ISSUE TITLE
AttributeError: 'Unparser' object has no attribute '_AsyncWith'

### ISSUE THREAD

**Issue by rbunn80110** [simonpercivall/astunparse#3]
It appears the "async with" construct is not yet supported?  If it should work let me know and I can submit all the necessary bug details.

**Comment by simonpercivall** [comment]
It should work, but you're correct, it doesn't.

**Comment by rbunn80110** [comment]
That's cool, glad to hear I'm not just doing something wrong.  Is there a plan to fix this any time soon?  Can I be of assistance in helping to write the code to fix the problem?

**Comment by rbunn80110** [comment]
So I just checked in code that fixes the problems with AsyncWait and AsyncFor.  I don't see my code changes in master so I assume you have to approve of them first?  Let me know if the changes aren't there or if I made any stupid mistakes.  This is my very first contribution to an open source project.  :)

**Comment by rbunn80110** [comment]
[unparser.zip](https://github.com/simonpercivall/astunparse/files/159922/unparser.zip)
[test_unparse.zip](https://github.com/simonpercivall/astunparse/files/159923/test_unparse.zip)

**Comment by rbunn80110** [comment]
Those are the only two files I changed.

**Comment by simonpercivall** [comment]
Hi! For me to see them you have to open a pill request from your fork to this repository.

**Comment by mbdevpl** [comment]
@rbunn80110 I've copied the code from here, modified it and created a pull request. Let me know what you think.

**Comment by simonpercivall** [comment]
Fixed by PR #6.
