### ISSUE TITLE
v1.6.1 not tagged on GitHub

### ISSUE THREAD

**Issue by hroncok** [simonpercivall/astunparse#34]
Hi. I want to package astunparse to Fedora, as it is a transitive dependency of Pythran.

I'd liek to run the tests when i build the package. The tests are however missing form the sdist tarball on PyPI, see https://github.com/simonpercivall/astunparse/pull/33

So I wanted to use the tagged tarball from GtiHub instead, but the most recent version 1.6.1 is not tagged. Could you please tag it?

**Comment by simonpercivall** [comment]
Thanks! I pushed the missing tag, and merged your PR, and bumped to 1.6.2.
