### ISSUE TITLE
Version number was not bumped to 1.6.2 with latest release

### ISSUE THREAD

**Issue by hoechenberger** [simonpercivall/astunparse#35]
The version number [is still at 1.6.1](https://github.com/simonpercivall/astunparse/blob/431bdfb5a32cf1acad8c834643844429939e04d4/lib/astunparse/__init__.py#L8) with the latest release. It ought to be at 1.6.2.

**Comment by simonpercivall** [comment]
You're looking at a commit before 1.6.2. Please check the 1.6.2 tag instead.

**Comment by hoechenberger** [comment]
Oh I see, I was confused because `master` reports the version to be `1.6.1`.

**Comment by simonpercivall** [comment]
*sigh* Right you are, I pushed the tag but not the branch. Fixed, and thanks.

**Comment by hoechenberger** [comment]
Thank you!
