### ISSUE TITLE
_Return Function does not check if a return statement has a value in unparse.py

### ISSUE THREAD

**Issue by NoahGaeta** [simonpercivall/astunparse#45]
It is legal to do this
'''\
def f():
    return
'''
A fix for the _Return function is this:
'''
    def _Return(self, t):
        self.fill("return")
        if hasattr(t, 'value'):
            if t.value:
                self.write(" ")
                self.dispatch(t.value)
'''

**Comment by isidentical** [comment]
it works as expected on "valid" nodes.
```py
>>> print(astunparse.unparse(ast.parse("def x(): return")))
def x():
    return
```

**Comment by NoahGaeta** [comment]
Huh, interesting. I wrote a test for it and I could've swore it failed but I re-tested it and it passed. I thought I hit a corner case with this, sorry about that.
